// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'zotodo-automatic-add'
  | 'zotodo-due-string'
  | 'zotodo-ignore-collections'
  | 'zotodo-include-note'
  | 'zotodo-labels'
  | 'zotodo-list-of-wildcards'
  | 'zotodo-menu-create-task'
  | 'zotodo-menu-preferences'
  | 'zotodo-note-format'
  | 'zotodo-preferences-pane'
  | 'zotodo-preferences-window'
  | 'zotodo-priority'
  | 'zotodo-project'
  | 'zotodo-section'
  | 'zotodo-set-due'
  | 'zotodo-task-format'
  | 'zotodo-todoist-settings'
  | 'zotodo-todoist-token'
  | 'zotodo-zotero-settings';
