// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "automatic_add": boolean;
      "ignore_collections": string;
      "include_note": boolean;
      "note_format": string;
      "due_string": string;
      "priority": number;
      "project": string;
      "section": string;
      "set_due": boolean;
      "labels": string;
      "task_format": string;
      "todoist_token": string;
    };
  }
}
